### ISSUE TITLE
Could Brazilians participate?

### ISSUE THREAD

**Issue by MSathler** [space-ros/docs#31]
I'm Brazilian and my colleagues and I want to participate, but we're Brazilian and we saw that we needed to be part of the “designated country” to participate. We didn't see Brazil in any designated country in the rules, but Brazil participates in the World Trade Organization WTO with is a first item, could you help us confirm if it's possible?

Regards.

**Comment by Bckempa** [comment]
Is this related to the "NASA Space ROS Sim Summer Sprint Challenge"? The GitHub issues are for issues with the Space ROS distribution itself, not the challenge. Please use the contact info provided in the freelancer posting for questions about the challenge.
