### ISSUE TITLE
Complete the documentation site

### ISSUE THREAD

**Issue by mjeronimo** [space-ros/docs#7]
This is meta issue to contain the list of pages to be completed:

**Michael**
- [x] index.rst
- [x] Introduction.rst
- [x] Introduction/About-SpaceROS.rst
- [x] Introduction/How-SpaceROS-Differs.rst
- [x] Getting-Started.rst
- [x] Demos.rst
- [x] Tutorials.rst
- [x] How-To-Guides.rst
- [x] Related-Projects.rst
- [x] The-Space-ROS-Project/Contributing.rst
- [x] Related-Projects/Cobra.rst
- [x] Related-Projects/IKOS.rst
- [x] Related-Projects/Doorstop.rst
- [x] Related-Projects/FRET.rst
- [x] How-To-Guides/Use-Cobra.rst

**Steven!**
- [ ] Introduction/Dev-And-Release-Model.rst
- [ ] Getting-Started/Docker-Images.rst
- [ ] Getting-Started/Building-From-Source.rst
- [x] Tutorials/First-Time-Building.rst
- [ ] How-To-Guides/Reproducing-CI-Locally.rst

**Dharini**
- [ ] Demos/Mars-Rover.rst
- [ ] Demos/Canadarm.rst
- [ ] How-To-Guides/Use-Simulation-Assets.rst

**Audrow**
- [x] How-To-Guides/Use-The-Dashboard.rst
- [ ] How-To-Guides/Use-VSCode-With-Docker.rst

**Geoff**
- [ ] Tutorials/Eventing-And-Telemetry.rst

**Anastasia and Ivan**
- [ ] Tutorials/Requirements-Tools-And-Processes.rst

**Morgan**
- [ ] Tutorials/Run-On-RTEMS.rst

**William**
- [ ] How-To-Guides/Use-Custom-Allocator.rst

**Ian**
- [x] How-To-Guides/MC-DC-Testing-Tool.rst

**Comment by audrow** [comment]
An example of how to use details:

- [ ] Item 1
  <details><summary>Some text</summary>

    Some details

    ```bash
    echo hi
    ```

  </details>

- [ ] Item 2

**Comment by audrow** [comment]
> * How-To-Guides/Use-VSCode-With-Docker.rst

https://github.com/space-ros/docs/pull/19

**Comment by Bckempa** [comment]
We should split the remaining tasks into backlog issues and close this long-running meta issue since it is targeted at developers no longer on the project.

**Comment by ivanperez-keera** [comment]
I vote to simply close this meta-issue altogether. There's no need to split this into smaller issues for anything that is not ticked in the list above. Future cleaning and natural improvements on the page will address anything that needs addressing.

**Comment by Bckempa** [comment]
Since all the referenced pages exist to stand-in for future work and the referenced people are not actively assigned to this project I concur
